import { useEffect, useRef, useState } from 'react';
import { MarkdownPreviewPane } from './MarkdownPreviewPane';

interface FixFormatPreviewDialogProps {
  open: boolean;
  filePath: string | null;
  originalMarkdown: string;
  proposedMarkdown: string;
  model: string;
  onAccept: () => void;
  onReject: () => void;
}

type ViewMode = 'rendered' | 'source' | 'compare';

const FOCUSABLE_SELECTOR =
  'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])';

export function FixFormatPreviewDialog({
  open,
  filePath,
  originalMarkdown,
  proposedMarkdown,
  model,
  onAccept,
  onReject,
}: FixFormatPreviewDialogProps) {
  const [viewMode, setViewMode] = useState<ViewMode>('rendered');
  const dialogRef = useRef<HTMLDivElement | null>(null);
  const previouslyFocusedRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (!open) {
      return;
    }
    setViewMode('rendered');
  }, [open]);

  useEffect(() => {
    if (!open) {
      return;
    }

    previouslyFocusedRef.current = document.activeElement as HTMLElement | null;
    const focusables = dialogRef.current?.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR);
    focusables?.[0]?.focus();

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        event.preventDefault();
        onReject();
        return;
      }
      if (event.key !== 'Tab' || !dialogRef.current) {
        return;
      }
      const nodes = Array.from(dialogRef.current.querySelectorAll<HTMLElement>(FOCUSABLE_SELECTOR));
      if (!nodes.length) {
        event.preventDefault();
        return;
      }
      const first = nodes[0];
      const last = nodes[nodes.length - 1];
      const active = document.activeElement as HTMLElement | null;
      if (event.shiftKey) {
        if (active === first || active === dialogRef.current) {
          event.preventDefault();
          last.focus();
        }
      } else if (active === last) {
        event.preventDefault();
        first.focus();
      }
    };

    document.addEventListener('keydown', onKeyDown);
    return () => {
      document.removeEventListener('keydown', onKeyDown);
      previouslyFocusedRef.current?.focus();
    };
  }, [open, onReject]);

  if (!open) {
    return null;
  }

  return (
    <div className="modal-backdrop" role="presentation" onClick={onReject}>
      <div
        className="modal-dialog fix-format-dialog"
        role="dialog"
        aria-modal="true"
        aria-labelledby="fix-format-title"
        ref={dialogRef}
        tabIndex={-1}
        onClick={(event) => event.stopPropagation()}
      >
        <header className="fix-format-header">
          <div>
            <h2 id="fix-format-title">Proposed formatting</h2>
            <p className="fix-format-subtitle">
              Generated by <code>{model}</code>. Review before applying — no changes have been made
              to your file yet.
            </p>
          </div>
          <div className="fix-format-view-toggle" role="tablist" aria-label="View mode">
            <button
              type="button"
              role="tab"
              aria-selected={viewMode === 'rendered'}
              className={viewMode === 'rendered' ? 'tab active' : 'tab'}
              onClick={() => setViewMode('rendered')}
            >
              Preview
            </button>
            <button
              type="button"
              role="tab"
              aria-selected={viewMode === 'source'}
              className={viewMode === 'source' ? 'tab active' : 'tab'}
              onClick={() => setViewMode('source')}
            >
              Source
            </button>
            <button
              type="button"
              role="tab"
              aria-selected={viewMode === 'compare'}
              className={viewMode === 'compare' ? 'tab active' : 'tab'}
              onClick={() => setViewMode('compare')}
            >
              Compare
            </button>
          </div>
        </header>

        <div className="fix-format-body">
          {viewMode === 'rendered' ? (
            <div className="fix-format-pane">
              <MarkdownPreviewPane filePath={filePath} markdown={proposedMarkdown} />
            </div>
          ) : viewMode === 'source' ? (
            <textarea
              className="fix-format-source"
              readOnly
              value={proposedMarkdown}
              aria-label="Proposed markdown source"
            />
          ) : (
            <div className="fix-format-compare">
              <div className="fix-format-compare-pane">
                <h3>Before</h3>
                <textarea
                  className="fix-format-source"
                  readOnly
                  value={originalMarkdown}
                  aria-label="Original markdown source"
                />
              </div>
              <div className="fix-format-compare-pane">
                <h3>After</h3>
                <textarea
                  className="fix-format-source"
                  readOnly
                  value={proposedMarkdown}
                  aria-label="Proposed markdown source"
                />
              </div>
            </div>
          )}
        </div>

        <div className="modal-actions fix-format-actions">
          <button type="button" className="danger-btn" onClick={onReject}>
            Reject
          </button>
          <button type="button" className="save-button" onClick={onAccept}>
            Accept changes
          </button>
        </div>
      </div>
    </div>
  );
}
